name: Deploy Javadoc

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy JavaDoc 🚀
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.4.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: javadoc
          java-version: 17
          project: gradle
          custom-command: javadoc -J"-Duser.language=en" noppes.npcs.api -subpackages noppes --class-path libs/*:. --source-path . -link https://nekoyue.github.io/ForgeJavaDocs-NG/javadoc/1.18.2/ -d build/docs/javadoc --ignore-source-errors -locale en_US -overview overview.html -overview overview.html -use -windowtitle "Custom NPCs API" -quiet